export const ASSETS_PACK_NAME = 'game-assets';

export const ASSET_KEYS = {
  yacht: {
    normal: 'yacht-normal',
    gold: 'yacht-gold',
  },
  common: {
    playFieldGlow: 'play-field-glow',
    energy: 'energy',
    timeBonus: 'time-bonus',
    moneyDown: 'money-down',
    moneyUp: 'money-up',
    moneyChangeDown: 'money-change-down',
    moneyChangeNo: 'money-change-no',
    moneyChangeUp: 'money-change-up',
  },
  shadows: {
    energy: 'energy-shadow',
    timeBonus: 'bonus-time-shadow',
  },
  level1: {
    waterBackground: 'sea-lvl-1',
    harbor: 'harbor-lvl-1',
    island: 'island-lvl-1',
    solidObstacle: 'solid-obstacle-lvl-1',
    whirlpool: 'whirlpool-lvl-1',
  },
  level2: {
    waterBackground: 'sea-lvl-2',
    harbor: 'harbor-lvl-2',
    island: 'island-lvl-2',
    solidObstacle: 'solid-obstacle-lvl-2',
    whirlpool: 'whirlpool-lvl-2',
  },
  level3: {
    waterBackground: 'sea-lvl-3',
    harbor: 'harbor-lvl-3',
    island: 'island-lvl-3',
    solidObstacle: 'solid-obstacle-lvl-3',
    whirlpool: 'whirlpool-lvl-3',
  },
  sounds: {
    interfaceMusic: 'interface-music',
    gameplayMusic: 'gameplay-music',
    bong1: 'bong-1',
    chords1: 'chords-1',
    chords3: 'chords-3',
    drop1: 'drop-1',
    drop2: 'drop-2',
    drop3: 'drop-3',
    glass1: 'glass-1',
    glass5: 'glass-5',
    maximize5: 'maximize-5',
    minimize5: 'minimize-5',
    minimize6: 'minimize-6',
    noise1: 'noise-1',
    select1: 'select-1',
    select2: 'select-2',
  },
} as const;
